### PR TITLE
Add support for AMD

### PR DESCRIPTION
**Pull request by apsdehal**
As for our transition of jQuery UI to intern testing framework, we need to alias QUnit as intern!qunit and require it through amd. It would be better to have support for both global and amd modules.

### CODE REVIEW

**Comment by scottgonzalez** [comment]
@JamesMGreene ping

**Comment by TIES-NPD** [comment]
I guess my hesitancy is based on the assumption of an AMD dependency named `"qunit"`.

In my past experience, AMD advocates like @jrburke typically recommend against loading testing frameworks like QUnit asynchronously, so this would also be a deviation from that line of thinking as well.

Neither is a deal breaker but they definitely give me pause.

Finally, if I'm going to add AMD support, seems like it would also be the right time to Node.js support as well.

**Comment by scottgonzalez** [comment]
QUnit already has AMD support, so the argument that testing frameworks shouldn't be loaded asynchronously is irrelevant as the framework itself already supports it and projects are already doing it.

As for being hesitant about using the name "qunit", going by that logic, AMD would not work at all, as no dependencies would ever be named.

**Comment by TIES-NPD** [comment]
> As for being hesitant about using the name "qunit", going by that logic, AMD would not work at all, as no dependencies would ever be named.

I would argue that this is AMD's biggest flaw. Combining dependencies isn't a big deal because that they can typically be controlled by a module configuration. However, when a dependency is declared within another dependency, things can get murkier.

**Comment by JamesMGreene** [comment]
> As for being hesitant about using the name "qunit", going by that logic, AMD would not work at all, as no dependencies would ever be named.

I would argue that this is AMD's biggest flaw. Combining dependencies isn't a big deal because that they can typically be controlled by a module configuration. However, when a dependency is declared within another dependency, things can get murkier.

**Comment by JamesMGreene** [comment]
Merged + added Node.js/CommonJS support, released/published as `v2.0.0`.

**Comment by scottgonzalez** [comment]
Thanks :-)

**Pull request merged**
